// dotnet-codereview-framework — src/report/markdown.js
// Author: Amr Kadry (github.com/Amrkadry) · MIT License
'use strict';
/**
 * SINGLE-FILE MARKDOWN PROJECTION — data/report.md
 *
 * The Obsidian vault (src/report/vault.js) is the rich human projection; this file is the
 * PORTABLE one: one document, every finding, each with a STABLE ANCHOR id so an AI pass (or a
 * human's deep link, or a CI comment) can locate a finding even when titles change.
 *
 * Anchors are literal HTML (`<a id="SEC-INJ-001"></a>`) rather than heading-derived slugs:
 * heading slugs change when a title is edited, and the findingId is the only stable name a
 * finding has (it is assigned after correlation to a deterministic order, and the AI-report
 * mode addresses findings by exactly this id).
 *
 * This file is a PROJECTION of data/report.json — regenerate, never hand-edit. ai-report mode
 * (src/adapters/ai-review.js) does not edit this file; it enriches the vault's per-finding
 * pages, which carry the same ids.
 */

const fs = require('fs');
const path = require('path');

const SEV_ORDER = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
const esc = s => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const anchor = f => f.findingId || 'unlinked';

function section(f) {
  const found = (f.sources || []).filter(s => s.status === 'REPORTED').map(s => s.tool);
  const missed = (f.sources || []).filter(s => s.status === 'MISSED').map(s => s.tool);
  const L = [];
  L.push(`<a id="${esc(anchor(f))}"></a>`, '');
  L.push(`## ${esc(anchor(f))} — ${esc(f.title)}`, '');
  L.push('| Field | Value |', '|---|---|');
  L.push(`| Severity | **${f.severity}** |`);
  L.push(`| CVSS | ${f.cvss ? `${f.cvss.score} (${f.cvss.severity})` : 'N/A'} |`);
  L.push(`| Confidence | ${f.confidence} |`);
  L.push(`| Category | ${esc(f.category)}${f.subcategory ? ' / `' + esc(f.subcategory) + '`' : ''} |`);
  L.push(`| CWE | ${(f.cwe || []).join(', ') || '—'} |`);
  L.push(`| Location | \`${esc(f.location && f.location.file)}${f.location && f.location.startLine ? ':' + f.location.startLine : ''}\` |`);
  L.push(`| Found by | ${found.join(', ') || '—'} |`);
  L.push(`| Missed by | ${missed.join(', ') || '—'} |`);
  L.push(`| Status | ${f.status || 'OPEN'} |`);
  if ((f.tests || []).length) L.push(`| Catalog cases | ${(f.tests || []).map(t => '`' + t + '`').join(' ')} |`);
  if (f.problem) L.push('', '**Problem.** ' + esc(f.problem));
  if (f.impact) L.push('', '**Impact.** ' + esc(f.impact));
  if (f.recommendation) L.push('', '**Fix.** ' + esc(f.recommendation));
  if (f.evidence && f.evidence.snippet) {
    L.push('', '```' + (f.evidence.language || 'csharp'), f.evidence.snippet, '```');
    if (f.evidence.redacted) L.push('', '*Secret material redacted by the adapter.*');
  }
  L.push('');
  return L.join('\n');
}

/**
 * Build the single-file markdown report.
 * @param {object} args { findings, summary, project, stats }
 */
function buildMarkdown(args) {
  const { findings = [], summary, project = {}, stats } = args;
  const L = [];
  L.push(`# Code review — ${project.name || 'project'}`, '');
  L.push(`> Generated by **dotnet-codereview-framework** on ${new Date().toISOString()}.`,
    '> A projection of `data/report.json` — the canonical source of truth. Regenerate, never edit.',
    '> Every finding carries a stable anchor (`<a id="FINDING-ID">`); the id in the table is the link target.', '');

  if (summary && summary.totals) {
    L.push('| Severity | Count |', '|---|---|');
    for (const s of SEV_ORDER) {
      const k = s.toLowerCase();
      if (summary.totals[k]) L.push(`| ${s} | ${summary.totals[k]} |`);
    }
    L.push(`| **Total** | **${summary.totals.all || findings.length}** |`, '');
  }
  if (stats) {
    L.push(`_${stats.inputFindings} raw finding(s) from all sources correlated into ` +
      `${stats.canonicalFindings} canonical (${stats.mergedAway} merged as duplicates, ` +
      `${stats.multiToolConfirmed} confirmed by more than one tool)._`, '');
  }

  L.push('| Finding | Severity | Location |', '|---|---|---|');
  for (const f of findings) {
    L.push(`| [${esc(anchor(f))}](#${encodeURIComponent(anchor(f))}) ${esc(f.title).slice(0, 90)} | ${f.severity} | \`${esc(f.location && f.location.file)}\` |`);
  }
  L.push('');
  for (const s of SEV_ORDER) {
    const group = findings.filter(f => f.severity === s);
    if (!group.length) continue;
    L.push(`---`, '', `# ${s}`, '');
    for (const f of group) L.push(section(f));
  }
  return L.join('\n');
}

/** Write data/report.md under the report directory. Returns the path written. */
function writeMarkdown(reportDir, args) {
  const p = path.join(reportDir, 'data', 'report.md');
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, buildMarkdown(args));
  return p;
}

module.exports = { buildMarkdown, writeMarkdown, anchor };
